run:
  timeout: 5m
  go: '1.22'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
    - exportloopref
    - nolintlint
    - revive
    - gocritic
    - gocyclo
    - dupl
    - prealloc
    - bodyclose

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    enable-all: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      - whyNoLint

  revive:
    rules:
      - name: exported
        arguments: ["checkPrivateReceivers", "sayRepetitiveInsteadOfStutters"]

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - gocritic

    # Exclude known linters from partially hard-to-fix issues
    - linters:
        - gosec
      text: "G304: Potential file inclusion via variable"

  max-same-issues: 50
  max-issues-per-linter: 50

  # Show only new issues created after git revision `REV`
  # new-from-rev: HEAD